### ISSUE TITLE
configparser.NoSectionError: No section: 'main'

### ISSUE THREAD

**Issue by XiaoFengZizz** [misakamikodo/mhxy_script#37]
运行pyqt脚本报错，
Traceback (most recent call last):
  File "d:\mymhxy\ui\mhxy_pyqt.py", line 328, in <module>
    MyUiStart = MhxyApplication()
                ^^^^^^^^^^^^^^^^^
  File "d:\mymhxy\ui\mhxy_pyqt.py", line 51, in __init__
    self.cusomer_ipt.setText(self.conn.get('main', 'lastscript'))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\configparser.py", line 759, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\configparser.py", line 1132, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'main'

script.ini  这个文件里边
[main]
dir = D:\mymhxy   路径改为了存放脚本的根目录
 
start.bat 里边
:: 改成绝对目录
start pythonw "D:\mymhxy\ui\mhxy_pyqt.py"  这里也改了

**Comment by misakamikodo** [comment]
这是没获取到script.ini文件，mhxy_pyqt.py第40行self.file_path = os.path.join(os.path.abspath('.'), r'script.ini')；是获取这个文件的代码，os.path是当前工作目录可以debug或者打印看看是不是不对，如果通过编辑器里在别的文件夹启动会导致这个不对，这时需要通过os.chdir改变一下。

**Comment by misakamikodo** [comment]
或者把这个文件迁移到对应目录去
