### ISSUE TITLE
我设置了对应分辨率，好像它移动不到0，0

### ISSUE THREAD

**Issue by rainsdf** [misakamikodo/mhxy_script#4]
PS D:\mhxy_script-master> python game_process.py
<Win32Window left="36", top="239", width="648", height="513", title="梦幻西游：时空">
处理后： <Win32Window left="71", top="0", width="907", height="707", title="梦幻西游：时空">
<Win32Window left="-32000", top="-32000", width="160", height="28", title="梦幻西游：时空">
Traceback (most recent call last):
  File "D:\mhxy_script-master\game_process.py", line 84, in <module>
    resize.moveZhuomianban()
  File "D:\mhxy_script-master\game_process.py", line 29, in moveZhuomianban
    self.__moveZhuomianbanFunc(niceSize)
  File "D:\mhxy_script-master\game_process.py", line 16, in __moveZhuomianbanFunc
    pyautogui.moveTo(item.right - resizeOffset[0], item.bottom - resizeOffset[1])
  File "C:\Users\WF\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyautogui\__init__.py", line 598, in wrapper
    returnVal = wrappedFunction(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WF\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyautogui\__init__.py", line 1283, in moveTo
    _mouseMoveDrag("move", x, y, 0, 0, duration, tween)
  File "C:\Users\WF\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyautogui\__init__.py", line 1509, in _mouseMoveDrag
    failSafeCheck()
  File "C:\Users\WF\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyautogui\__init__.py", line 1722, in failSafeCheck
    raise FailSafeException(
pyautogui.FailSafeException: PyAutoGUI fail-safe triggered from mouse moving to a corner of the screen. To disable this fail-safe, set pyautogui.FAILSAFE to False. DISABLING FAIL-SAFE IS NOT RECOMMENDED.
PS D:\mhxy_script-master>

**Comment by rainsdf** [comment]
是双屏导致的问题吗？

**Comment by misakamikodo** [comment]
出问题的手动点一下窗口就没这个问题了，为什么会这样我就不知道了

**Comment by misakamikodo** [comment]
> 出问题的手动点一下窗口就没这个问题了，为什么会这样我就不知道了

出问题的手动点一下窗口就没这个问题了，为什么会这样我就不知道了

**Comment by misakamikodo** [comment]
> 是双屏导致的问题吗？

出问题的手动点一下窗口就没这个问题了，为什么会这样我就不知道了

**Comment by rainsdf** [comment]
谢谢大佬，我再研究一下
