### ISSUE TITLE
请问下大佬，python版本是多少？还有python opencv版本

### ISSUE THREAD

**Issue by brian0101** [misakamikodo/mhxy_script#9]
Traceback (most recent call last):
  File "C:\Users\24945\Downloads\mhxy_script-master\mhxy_script-master\game_process.py", line 4, in <module>
    from mhxy import *
  File "C:\Users\24945\Downloads\mhxy_script-master\mhxy_script-master\mhxy.py", line 5, in <module>
    import pyautogui
  File "C:\Users\24945\anaconda3\lib\site-packages\pyautogui\__init__.py", line 180, in <module>
    import pyscreeze
  File "C:\Users\24945\anaconda3\lib\site-packages\pyscreeze\__init__.py", line 25, in <module>
    import cv2
  File "C:\Users\24945\anaconda3\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\24945\anaconda3\lib\site-packages\cv2\__init__.py", line 97, in bootstrap
    from . load_config_py3 import exec_file_wrapper
ValueError: source code string cannot contain null bytes

**Comment by misakamikodo** [comment]
brotlipy==0.7.0
certifi==2022.5.18.1
cffi==1.15.0
charset-normalizer==2.0.4
cryptography==37.0.1
idna==3.3
MouseInfo==0.1.3
numpy==1.21.6
opencv-contrib-python==4.6.0.66
Pillow==9.1.1
pip==21.2.4
playsound==1.3.0
PyAutoGUI==0.9.53
pycparser==2.21
PyGetWindow==0.0.9
PyMsgBox==1.0.9
pyOpenSSL==22.0.0
pyperclip==1.8.2
PyRect==0.2.0
PyScreeze==0.1.28
PySocks==1.7.1
pytweening==1.0.4
requests==2.27.1
setuptools==61.2.0
urllib3==1.26.9
wheel==0.37.1
win-inet-pton==1.1.0
wincertstore==0.2

python是3.9
